const CARDS = [
  // A2 SOSTANTIVI
  {it:"Consiglio",en:"Advice",emoji:"💬",tag:"a2",pos:"s.",ex:"She gave me some really useful advice about the interview."},
  {it:"Quantità",en:"Amount",emoji:"🔢",tag:"a2",pos:"s.",ex:"A large amount of money was raised for charity."},
  {it:"Discussione",en:"Argument",emoji:"💥",tag:"a2",pos:"s.",ex:"They had a big argument about money last night."},
  {it:"Attenzione",en:"Attention",emoji:"👁️",tag:"a2",pos:"s.",ex:"Please pay attention to the safety instructions."},
  {it:"Comportamento",en:"Behaviour",emoji:"🪞",tag:"a2",pos:"s.",ex:"His behaviour at the party was very rude."},
  {it:"Beneficio / Vantaggio",en:"Benefit",emoji:"✅",tag:"a2",pos:"s.",ex:"The main benefit of exercise is that it improves your mood."},
  {it:"Possibilità",en:"Chance",emoji:"🎲",tag:"a2",pos:"s.",ex:"This is a great chance to improve your English."},
  {it:"Carattere",en:"Character",emoji:"🎭",tag:"a2",pos:"s.",ex:"She has a very warm and friendly character."},
  {it:"Scelta",en:"Choice",emoji:"🔀",tag:"a2",pos:"s.",ex:"You have to make a choice between the two options."},
  {it:"Cliente",en:"Customer",emoji:"🛒",tag:"a2",pos:"s.",ex:"The customer complained about the quality of the food."},
  {it:"Pericolo",en:"Danger",emoji:"⚠️",tag:"a2",pos:"s.",ex:"The hikers were in danger because of the storm."},
  {it:"Decisione",en:"Decision",emoji:"⚖️",tag:"a2",pos:"s.",ex:"It was a very difficult decision to make."},
  {it:"Sviluppo",en:"Development",emoji:"📊",tag:"a2",pos:"s.",ex:"There has been rapid development in this area of technology."},
  {it:"Svantaggio",en:"Disadvantage",emoji:"📉",tag:"a2",pos:"s.",ex:"The main disadvantage is the high cost of living."},
  {it:"Sogno",en:"Dream",emoji:"💭",tag:"a2",pos:"s.",ex:"Her dream is to become a professional musician."},
  {it:"Effetto",en:"Effect",emoji:"💡",tag:"a2",pos:"s.",ex:"Stress can have a negative effect on your health."},
  {it:"Energia",en:"Energy",emoji:"⚡",tag:"a2",pos:"s.",ex:"We need to find cleaner sources of energy."},
  {it:"Errore",en:"Error",emoji:"❌",tag:"a2",pos:"s.",ex:"There were several errors in the report."},
  {it:"Esperienza",en:"Experience",emoji:"🌍",tag:"a2",pos:"s.",ex:"Working abroad was an amazing experience."},
  {it:"Paura",en:"Fear",emoji:"😨",tag:"a2",pos:"s.",ex:"She has a fear of flying that stops her travelling."},
  {it:"Obiettivo",en:"Goal",emoji:"🥅",tag:"a2",pos:"s.",ex:"My goal is to speak English fluently by next year."},
  {it:"Governo",en:"Government",emoji:"🏛️",tag:"a2",pos:"s.",ex:"The government has announced new plans for education."},
  {it:"Abitudine",en:"Habit",emoji:"📅",tag:"a2",pos:"s.",ex:"It is a bad habit to eat in front of the television."},
  {it:"Speranza",en:"Hope",emoji:"🌈",tag:"a2",pos:"s.",ex:"There is still hope that they will find a solution."},
  {it:"Industria",en:"Industry",emoji:"🏭",tag:"a2",pos:"s.",ex:"The tourism industry is very important to this region."},
  {it:"Conoscenza",en:"Knowledge",emoji:"📚",tag:"a2",pos:"s.",ex:"A good knowledge of English is very useful at work."},
  {it:"Legge",en:"Law",emoji:"⚖️",tag:"a2",pos:"s.",ex:"It is against the law to drive without a seatbelt."},
  {it:"Stile di vita",en:"Lifestyle",emoji:"🌿",tag:"a2",pos:"s.",ex:"Moving to the countryside changed her lifestyle completely."},
  {it:"Fortuna",en:"Luck",emoji:"🍀",tag:"a2",pos:"s.",ex:"You need a lot of luck to win the lottery."},
  {it:"Matrimonio",en:"Marriage",emoji:"💍",tag:"a2",pos:"s.",ex:"Their marriage has lasted for over thirty years."},
  {it:"Materiale",en:"Material",emoji:"🧱",tag:"a2",pos:"s.",ex:"The bag is made from recycled material."},
  {it:"Media",en:"Media",emoji:"📺",tag:"a2",pos:"s.",ex:"The media reported the story very differently."},
  {it:"Ricordo / Memoria",en:"Memory",emoji:"🧠",tag:"a2",pos:"s.",ex:"I have a very happy memory of our first holiday together."},
  {it:"Mente",en:"Mind",emoji:"💭",tag:"a2",pos:"s.",ex:"Keep an open mind when you meet new people."},
  {it:"Umore",en:"Mood",emoji:"😊",tag:"a2",pos:"s.",ex:"She is always in a good mood in the morning."},
  {it:"Rete",en:"Network",emoji:"🌐",tag:"a2",pos:"s.",ex:"She has built up a strong professional network."},
  {it:"Notizia",en:"News",emoji:"📰",tag:"a2",pos:"s.",ex:"Have you heard the news about the new shopping centre?"},
  {it:"Rumore",en:"Noise",emoji:"🔊",tag:"a2",pos:"s.",ex:"The noise from the street made it hard to sleep."},
  {it:"Opinione",en:"Opinion",emoji:"💬",tag:"a2",pos:"s.",ex:"In my opinion, the film was too long."},
  {it:"Opportunità",en:"Opportunity",emoji:"🚀",tag:"a2",pos:"s.",ex:"This job is a great opportunity to develop new skills."},
  {it:"Dolore",en:"Pain",emoji:"😢",tag:"a2",pos:"s.",ex:"She felt a sharp pain in her back after lifting the box."},
  {it:"Permesso",en:"Permission",emoji:"✅",tag:"a2",pos:"s.",ex:"You need permission from your manager to take the day off."},
  {it:"Personalità",en:"Personality",emoji:"🌟",tag:"a2",pos:"s.",ex:"She has a very warm and outgoing personality."},
  {it:"Popolazione",en:"Population",emoji:"👥",tag:"a2",pos:"s.",ex:"The population of this city has grown rapidly."},
  {it:"Potere",en:"Power",emoji:"💪",tag:"a2",pos:"s.",ex:"Knowledge is one of the greatest forms of power."},
  {it:"Problema",en:"Problem",emoji:"⚠️",tag:"a2",pos:"s.",ex:"We need to find a solution to this problem quickly."},
  {it:"Progresso",en:"Progress",emoji:"📈",tag:"a2",pos:"s.",ex:"She has made excellent progress with her English studies."},
  {it:"Qualità",en:"Quality",emoji:"⭐",tag:"a2",pos:"s.",ex:"The quality of the food at that restaurant is excellent."},
  {it:"Ragione",en:"Reason",emoji:"❓",tag:"a2",pos:"s.",ex:"What is the reason for the delay?"},
  {it:"Relazione",en:"Relationship",emoji:"❤️",tag:"a2",pos:"s.",ex:"She has a very good relationship with her colleagues."},
  {it:"Risposta",en:"Response",emoji:"💬",tag:"a2",pos:"s.",ex:"I sent an email but got no response."},
  {it:"Risultato",en:"Result",emoji:"📊",tag:"a2",pos:"s.",ex:"The result of the match was a surprise to everyone."},
  {it:"Ruolo",en:"Role",emoji:"🎭",tag:"a2",pos:"s.",ex:"Parents play a vital role in a child's education."},
  {it:"Regola",en:"Rule",emoji:"📏",tag:"a2",pos:"s.",ex:"The most important rule is to always tell the truth."},
  {it:"Stipendio",en:"Salary",emoji:"💰",tag:"a2",pos:"s.",ex:"The salary for this position is very competitive."},
  {it:"Sicurezza",en:"Security",emoji:"🔐",tag:"a2",pos:"s.",ex:"The airport has very strict security procedures."},
  {it:"Senso",en:"Sense",emoji:"💡",tag:"a2",pos:"s.",ex:"It makes sense to save money for the future."},
  {it:"Servizio",en:"Service",emoji:"🛎️",tag:"a2",pos:"s.",ex:"The customer service at that hotel was excellent."},
  {it:"Abilità",en:"Skill",emoji:"🎯",tag:"a2",pos:"s.",ex:"Problem solving is a skill that every employer looks for."},
  {it:"Soluzione",en:"Solution",emoji:"🧩",tag:"a2",pos:"s.",ex:"We need to find a long-term solution to this problem."},
  {it:"Velocità",en:"Speed",emoji:"⚡",tag:"a2",pos:"s.",ex:"The train travels at a speed of 300 kilometres per hour."},
  {it:"Standard",en:"Standard",emoji:"📏",tag:"a2",pos:"s.",ex:"The standard of work in this class is very high."},
  {it:"Forza",en:"Strength",emoji:"💪",tag:"a2",pos:"s.",ex:"Her greatest strength is her ability to stay calm under pressure."},
  {it:"Successo",en:"Success",emoji:"🏆",tag:"a2",pos:"s.",ex:"Hard work is the key to success."},
  {it:"Sistema",en:"System",emoji:"⚙️",tag:"a2",pos:"s.",ex:"The school has introduced a new grading system."},
  {it:"Compito",en:"Task",emoji:"📋",tag:"a2",pos:"s.",ex:"The first task is to read the instructions carefully."},
  {it:"Tecnologia",en:"Technology",emoji:"💻",tag:"a2",pos:"s.",ex:"Modern technology has changed the way we communicate."},
  {it:"Temperatura",en:"Temperature",emoji:"🌡️",tag:"a2",pos:"s.",ex:"The temperature will drop below zero tonight."},
  {it:"Tema",en:"Topic",emoji:"📌",tag:"a2",pos:"s.",ex:"Climate change is a very important topic today."},
  {it:"Tradizione",en:"Tradition",emoji:"🎎",tag:"a2",pos:"s.",ex:"It is a tradition to eat turkey at Christmas in England."},
  {it:"Traffico",en:"Traffic",emoji:"🚗",tag:"a2",pos:"s.",ex:"The traffic in the city centre is terrible during rush hour."},
  {it:"Trasporto",en:"Transport",emoji:"🚌",tag:"a2",pos:"s.",ex:"Public transport in this city is fast and reliable."},
  {it:"Tendenza",en:"Trend",emoji:"📈",tag:"a2",pos:"s.",ex:"There is a growing trend to work from home."},
  {it:"Valore",en:"Value",emoji:"💎",tag:"a2",pos:"s.",ex:"Family and friendship are the values I care about most."},
  {it:"Vista",en:"View",emoji:"🔭",tag:"a2",pos:"s.",ex:"The view from the top of the hill was absolutely stunning."},
  {it:"Peso",en:"Weight",emoji:"⚖️",tag:"a2",pos:"s.",ex:"She has been trying to lose weight for several months."},
  // A2 AGGETTIVI
  {it:"Attivo",en:"Active",emoji:"🏃",tag:"a2",pos:"agg.",ex:"She leads a very active lifestyle and goes to the gym daily."},
  {it:"Attraente",en:"Attractive",emoji:"✨",tag:"a2",pos:"agg.",ex:"The city centre has many attractive historic buildings."},
  {it:"Disponibile",en:"Available",emoji:"✅",tag:"a2",pos:"agg.",ex:"The doctor is not available until Thursday afternoon."},
  {it:"Medio",en:"Average",emoji:"📊",tag:"a2",pos:"agg.",ex:"The average temperature in July is around 28 degrees."},
  {it:"Brillante",en:"Brilliant",emoji:"💡",tag:"a2",pos:"agg.",ex:"She is a brilliant student who always gets top grades."},
  {it:"Attento",en:"Careful",emoji:"⚠️",tag:"a2",pos:"agg.",ex:"Be careful when you cross the road."},
  {it:"Certo",en:"Certain",emoji:"✅",tag:"a2",pos:"agg.",ex:"I am not certain what time the meeting starts."},
  {it:"Chiaro",en:"Clear",emoji:"💎",tag:"a2",pos:"agg.",ex:"The instructions were very clear and easy to follow."},
  {it:"Intelligente",en:"Clever",emoji:"🧠",tag:"a2",pos:"agg.",ex:"He is a very clever boy who learns everything quickly."},
  {it:"Comodo",en:"Comfortable",emoji:"😌",tag:"a2",pos:"agg.",ex:"This sofa is very comfortable to sit on."},
  {it:"Creativo",en:"Creative",emoji:"🎨",tag:"a2",pos:"agg.",ex:"She is very creative and loves making things by hand."},
  {it:"Pericoloso",en:"Dangerous",emoji:"⚠️",tag:"a2",pos:"agg.",ex:"Driving at high speed is very dangerous."},
  {it:"Diverso",en:"Different",emoji:"🔀",tag:"a2",pos:"agg.",ex:"People from different cultures have different traditions."},
  {it:"Diretto",en:"Direct",emoji:"➡️",tag:"a2",pos:"agg.",ex:"She gave a very direct answer to the question."},
  {it:"Deluso",en:"Disappointed",emoji:"😔",tag:"a2",pos:"agg.",ex:"I was really disappointed when they cancelled the concert."},
  {it:"Vuoto",en:"Empty",emoji:"🫙",tag:"a2",pos:"agg.",ex:"The bottle is completely empty, we need to buy more."},
  {it:"Enorme / Smisurato",en:"Enormous",emoji:"🐘",tag:"a2",pos:"agg.",ex:"The new shopping centre is absolutely enormous."},
  {it:"Eccellente",en:"Excellent",emoji:"⭐",tag:"a2",pos:"agg.",ex:"The food at that restaurant is absolutely excellent."},
  {it:"Famoso",en:"Famous",emoji:"🌟",tag:"a2",pos:"agg.",ex:"She is famous for her work in environmental protection."},
  {it:"Straniero",en:"Foreign",emoji:"🌍",tag:"a2",pos:"agg.",ex:"She speaks three foreign languages fluently."},
  {it:"Formale",en:"Formal",emoji:"👔",tag:"a2",pos:"agg.",ex:"Please dress formally for the job interview."},
  {it:"Fresco",en:"Fresh",emoji:"🍃",tag:"a2",pos:"agg.",ex:"I love the smell of fresh coffee in the morning."},
  {it:"Generale",en:"General",emoji:"🌐",tag:"a2",pos:"agg.",ex:"In general, people are living longer than before."},
  {it:"Enorme (colloquiale)",en:"Huge",emoji:"🏔️",tag:"a2",pos:"agg.",ex:"The concert attracted a huge crowd of fans."},
  {it:"Ideale",en:"Ideal",emoji:"✨",tag:"a2",pos:"agg.",ex:"This location is ideal for a family holiday."},
  {it:"Immediato",en:"Immediate",emoji:"⚡",tag:"a2",pos:"agg.",ex:"The medicine had an immediate effect on the pain."},
  {it:"Importante",en:"Important",emoji:"❗",tag:"a2",pos:"agg.",ex:"It is important to drink plenty of water every day."},
  {it:"Incredibile",en:"Incredible",emoji:"🤯",tag:"a2",pos:"agg.",ex:"The view from the top of the mountain was incredible."},
  {it:"Indipendente",en:"Independent",emoji:"🦅",tag:"a2",pos:"agg.",ex:"She is very independent and prefers to work alone."},
  {it:"Internazionale",en:"International",emoji:"🌍",tag:"a2",pos:"agg.",ex:"She has a lot of international experience in her field."},
  {it:"Probabile",en:"Likely",emoji:"🎯",tag:"a2",pos:"agg.",ex:"It is likely to rain tomorrow afternoon."},
  {it:"Locale",en:"Local",emoji:"📍",tag:"a2",pos:"agg.",ex:"I prefer to shop at local markets rather than supermarkets."},
  {it:"Principale",en:"Major",emoji:"⭐",tag:"a2",pos:"agg.",ex:"Pollution is one of the major problems facing the world."},
  {it:"Moderno",en:"Modern",emoji:"🏙️",tag:"a2",pos:"agg.",ex:"The office is in a very modern building in the city centre."},
  {it:"Nazionale",en:"National",emoji:"🏳️",tag:"a2",pos:"agg.",ex:"The national museum is free to visit on Sundays."},
  {it:"Naturale",en:"Natural",emoji:"🌿",tag:"a2",pos:"agg.",ex:"It is completely natural to feel nervous before an exam."},
  {it:"Necessario",en:"Necessary",emoji:"✅",tag:"a2",pos:"agg.",ex:"Is it really necessary to bring a formal letter?"},
  {it:"Nervoso",en:"Nervous",emoji:"😰",tag:"a2",pos:"agg.",ex:"She was very nervous before her driving test."},
  {it:"Normale",en:"Normal",emoji:"📏",tag:"a2",pos:"agg.",ex:"It is completely normal to make mistakes when learning."},
  {it:"Popolare",en:"Popular",emoji:"⭐",tag:"a2",pos:"agg.",ex:"This cafe is very popular with students and tourists."},
  {it:"Positivo",en:"Positive",emoji:"😊",tag:"a2",pos:"agg.",ex:"Try to stay positive even when things are difficult."},
  {it:"Possibile",en:"Possible",emoji:"✅",tag:"a2",pos:"agg.",ex:"Is it possible to change my appointment to Friday?"},
  {it:"Professionale",en:"Professional",emoji:"👔",tag:"a2",pos:"agg.",ex:"She always behaves in a very professional manner."},
  {it:"Raro",en:"Rare",emoji:"💎",tag:"a2",pos:"agg.",ex:"Snow is a rare event in southern Italy."},
  {it:"Recente",en:"Recent",emoji:"📅",tag:"a2",pos:"agg.",ex:"Have you read any recent news about the election?"},
  {it:"Regolare",en:"Regular",emoji:"🔁",tag:"a2",pos:"agg.",ex:"Regular exercise helps to reduce stress levels."},
  {it:"Responsabile",en:"Responsible",emoji:"⚖️",tag:"a2",pos:"agg.",ex:"She is responsible for managing the team budget."},
  {it:"Serio",en:"Serious",emoji:"😐",tag:"a2",pos:"agg.",ex:"This is a very serious matter that needs your attention."},
  {it:"Simile",en:"Similar",emoji:"🔗",tag:"a2",pos:"agg.",ex:"The two sisters have very similar personalities."},
  {it:"Semplice",en:"Simple",emoji:"🎯",tag:"a2",pos:"agg.",ex:"The instructions are very simple and easy to follow."},
  {it:"Specifico",en:"Specific",emoji:"🎯",tag:"a2",pos:"agg.",ex:"Could you give me a more specific answer please?"},
  {it:"Strano",en:"Strange",emoji:"🤔",tag:"a2",pos:"agg.",ex:"There is a strange smell coming from the kitchen."},
  {it:"Forte",en:"Strong",emoji:"💪",tag:"a2",pos:"agg.",ex:"You need a strong password to protect your account."},
  {it:"Adatto",en:"Suitable",emoji:"✅",tag:"a2",pos:"agg.",ex:"Is this film suitable for young children?"},
  {it:"Sorprendente",en:"Surprising",emoji:"😲",tag:"a2",pos:"agg.",ex:"It is surprising how quickly children learn languages."},
  {it:"Tradizionale",en:"Traditional",emoji:"🎎",tag:"a2",pos:"agg.",ex:"We ate a traditional Italian meal at Christmas."},
  {it:"Tipico",en:"Typical",emoji:"📏",tag:"a2",pos:"agg.",ex:"This is a typical example of how the system works."},
  {it:"Insolito",en:"Unusual",emoji:"🤔",tag:"a2",pos:"agg.",ex:"It is unusual to see snow here in April."},
  {it:"Prezioso",en:"Valuable",emoji:"💎",tag:"a2",pos:"agg.",ex:"This ring is very valuable, so please keep it safe."},
  // A2 VERBI
  {it:"Accettare",en:"Accept",emoji:"✅",tag:"a2",pos:"v.",ex:"She accepted the job offer without hesitation."},
  {it:"Conseguire / Ottenere",en:"Achieve",emoji:"🎯",tag:"a2",pos:"v.",ex:"With hard work you can achieve anything you want."},
  {it:"Influenzare",en:"Affect",emoji:"💡",tag:"a2",pos:"v.",ex:"Stress can affect your health in many different ways."},
  {it:"Permettere",en:"Allow",emoji:"✅",tag:"a2",pos:"v.",ex:"The teacher did not allow talking during the exam."},
  {it:"Comparire",en:"Appear",emoji:"👀",tag:"a2",pos:"v.",ex:"He appeared very calm during the interview."},
  {it:"Fare domanda",en:"Apply",emoji:"📋",tag:"a2",pos:"v.",ex:"I am going to apply for a job in London."},
  {it:"Litigare / Discutere",en:"Argue",emoji:"💬",tag:"a2",pos:"v.",ex:"They argue a lot but they always make up quickly."},
  {it:"Sistemare",en:"Arrange",emoji:"📅",tag:"a2",pos:"v.",ex:"Can you arrange a meeting for next Tuesday?"},
  {it:"Evitare",en:"Avoid",emoji:"🚫",tag:"a2",pos:"v.",ex:"Try to avoid eating too much sugar."},
  {it:"Comportarsi",en:"Behave",emoji:"🪞",tag:"a2",pos:"v.",ex:"The children behaved very well during the trip."},
  {it:"Prenotare",en:"Book",emoji:"📖",tag:"a2",pos:"v.",ex:"I need to book a table for two for Saturday evening."},
  {it:"Celebrare",en:"Celebrate",emoji:"🎉",tag:"a2",pos:"v.",ex:"We celebrated her birthday with a surprise party."},
  {it:"Controllare",en:"Check",emoji:"✅",tag:"a2",pos:"v.",ex:"Always check your work before handing it in."},
  {it:"Scegliere",en:"Choose",emoji:"🔀",tag:"a2",pos:"v.",ex:"It was very hard to choose between the two options."},
  {it:"Comunicare",en:"Communicate",emoji:"💬",tag:"a2",pos:"v.",ex:"It is important to communicate clearly with your team."},
  {it:"Lamentarsi",en:"Complain",emoji:"😤",tag:"a2",pos:"v.",ex:"He complained to the manager about the service."},
  {it:"Considerare",en:"Consider",emoji:"💭",tag:"a2",pos:"v.",ex:"You should consider all your options before deciding."},
  {it:"Continuare",en:"Continue",emoji:"▶️",tag:"a2",pos:"v.",ex:"Please continue with your work while I make a phone call."},
  {it:"Creare",en:"Create",emoji:"🎨",tag:"a2",pos:"v.",ex:"She has created a very successful business from scratch."},
  {it:"Dipendere",en:"Depend",emoji:"🔗",tag:"a2",pos:"v.",ex:"Your success depends on the effort you put in."},
  {it:"Sviluppare",en:"Develop",emoji:"📈",tag:"a2",pos:"v.",ex:"The company wants to develop new products next year."},
  {it:"Scoprire",en:"Discover",emoji:"🔍",tag:"a2",pos:"v.",ex:"Scientists have discovered a new treatment for the disease."},
  {it:"Discutere",en:"Discuss",emoji:"💬",tag:"a2",pos:"v.",ex:"We need to discuss the results of the survey."},
  {it:"Guadagnare",en:"Earn",emoji:"💰",tag:"a2",pos:"v.",ex:"How much do you earn in your current job?"},
  {it:"Apprezzare / Divertirsi",en:"Enjoy",emoji:"😊",tag:"a2",pos:"v.",ex:"I really enjoy cooking for family and friends."},
  {it:"Aspettarsi",en:"Expect",emoji:"🎯",tag:"a2",pos:"v.",ex:"I expect the report to be ready by Friday."},
  {it:"Spiegare",en:"Explain",emoji:"💡",tag:"a2",pos:"v.",ex:"Can you explain how this system works?"},
  {it:"Fallire",en:"Fail",emoji:"❌",tag:"a2",pos:"v.",ex:"She failed her driving test three times before passing."},
  {it:"Aggiustare",en:"Fix",emoji:"🔧",tag:"a2",pos:"v.",ex:"Can you fix this broken chair before the guests arrive?"},
  {it:"Seguire",en:"Follow",emoji:"➡️",tag:"a2",pos:"v.",ex:"Please follow the instructions carefully."},
  {it:"Aumentare",en:"Increase",emoji:"📈",tag:"a2",pos:"v.",ex:"The price of fuel has increased again this month."},
  {it:"Invitare",en:"Invite",emoji:"💌",tag:"a2",pos:"v.",ex:"She invited all her friends to her birthday party."},
  {it:"Gestire",en:"Manage",emoji:"📋",tag:"a2",pos:"v.",ex:"She manages a team of fifteen people at work."},
  {it:"Misurare",en:"Measure",emoji:"📏",tag:"a2",pos:"v.",ex:"Can you measure the length of this room please?"},
  {it:"Menzionare",en:"Mention",emoji:"💬",tag:"a2",pos:"v.",ex:"He mentioned that he was looking for a new job."},
  {it:"Notare",en:"Notice",emoji:"👁️",tag:"a2",pos:"v.",ex:"Did you notice anything unusual about his behaviour?"},
  {it:"Offrire",en:"Offer",emoji:"🎁",tag:"a2",pos:"v.",ex:"They offered her a very good salary for the new role."},
  {it:"Organizzare",en:"Organize",emoji:"📁",tag:"a2",pos:"v.",ex:"She organized the whole event by herself."},
  {it:"Partecipare",en:"Participate",emoji:"👥",tag:"a2",pos:"v.",ex:"Everyone is encouraged to participate in the discussion."},
  {it:"Praticare",en:"Practise",emoji:"🔁",tag:"a2",pos:"v.",ex:"You need to practise speaking English every day."},
  {it:"Preferire",en:"Prefer",emoji:"❤️",tag:"a2",pos:"v.",ex:"Do you prefer tea or coffee in the morning?"},
  {it:"Preparare",en:"Prepare",emoji:"📋",tag:"a2",pos:"v.",ex:"She spent two weeks preparing for the presentation."},
  {it:"Prevenire",en:"Prevent",emoji:"🛡️",tag:"a2",pos:"v.",ex:"Regular exercise can help prevent heart disease."},
  {it:"Proteggere",en:"Protect",emoji:"🛡️",tag:"a2",pos:"v.",ex:"We must protect the rainforest for future generations."},
  {it:"Fornire",en:"Provide",emoji:"🎁",tag:"a2",pos:"v.",ex:"The school provides free meals for all students."},
  {it:"Ridurre",en:"Reduce",emoji:"📉",tag:"a2",pos:"v.",ex:"We need to reduce the amount of plastic we use."},
  {it:"Rifiutare",en:"Refuse",emoji:"❌",tag:"a2",pos:"v.",ex:"She refused to answer any questions about her personal life."},
  {it:"Rispondere",en:"Respond",emoji:"💬",tag:"a2",pos:"v.",ex:"She did not respond to my message for three days."},
  {it:"Richiedere",en:"Require",emoji:"📋",tag:"a2",pos:"v.",ex:"This job requires excellent communication skills."},
  {it:"Cercare",en:"Search",emoji:"🔍",tag:"a2",pos:"v.",ex:"I searched online for information about the course."},
  {it:"Sembrare",en:"Seem",emoji:"🤔",tag:"a2",pos:"v.",ex:"She seems tired today, is she feeling all right?"},
  {it:"Vendere",en:"Sell",emoji:"🏷️",tag:"a2",pos:"v.",ex:"They sell fresh vegetables at the market every Saturday."},
  {it:"Inviare",en:"Send",emoji:"📤",tag:"a2",pos:"v.",ex:"Please send me the document by email before noon."},
  {it:"Risolvere",en:"Solve",emoji:"🧩",tag:"a2",pos:"v.",ex:"It took the team three days to solve the technical problem."},
  {it:"Spendere",en:"Spend",emoji:"💰",tag:"a2",pos:"v.",ex:"How much do you spend on food each week?"},
  {it:"Diffondersi",en:"Spread",emoji:"📡",tag:"a2",pos:"v.",ex:"News spreads very quickly on social media."},
  {it:"Rimanere",en:"Stay",emoji:"🏠",tag:"a2",pos:"v.",ex:"She decided to stay at home and rest instead of going out."},
  {it:"Rubare",en:"Steal",emoji:"🚨",tag:"a2",pos:"v.",ex:"Someone stole my bag on the train this morning."},
  {it:"Riuscire",en:"Succeed",emoji:"🏆",tag:"a2",pos:"v.",ex:"If you work hard you will succeed in the end."},
  {it:"Suggerire",en:"Suggest",emoji:"💡",tag:"a2",pos:"v.",ex:"I would like to suggest a different approach to this problem."},
  {it:"Sostenere / Appoggiare",en:"Support",emoji:"🤝",tag:"a2",pos:"v.",ex:"Her family supported her through a very difficult time."},
  {it:"Tendere",en:"Tend",emoji:"📈",tag:"a2",pos:"v.",ex:"People tend to eat more when they are stressed."},
  {it:"Avvertire",en:"Warn",emoji:"⚠️",tag:"a2",pos:"v.",ex:"The weather forecast warned of heavy snow overnight."},
  {it:"Vincere",en:"Win",emoji:"🏆",tag:"a2",pos:"v.",ex:"She worked very hard and finally won the competition."},
  // B1 SOSTANTIVI
  {it:"Realizzazione",en:"Achievement",emoji:"🏆",tag:"b1",pos:"s.",ex:"Finishing the marathon was a great personal achievement."},
  {it:"Accordo",en:"Agreement",emoji:"🤝",tag:"b1",pos:"s.",ex:"The two companies finally reached an agreement."},
  {it:"Ambizione",en:"Ambition",emoji:"🚀",tag:"b1",pos:"s.",ex:"Her ambition is to become a doctor."},
  {it:"Annuncio",en:"Announcement",emoji:"📢",tag:"b1",pos:"s.",ex:"The announcement was made at the start of the meeting."},
  {it:"Attitudine",en:"Attitude",emoji:"🧠",tag:"b1",pos:"s.",ex:"You need to change your attitude towards work."},
  {it:"Convinzione",en:"Belief",emoji:"💭",tag:"b1",pos:"s.",ex:"It is my belief that education changes lives."},
  {it:"Confine",en:"Border",emoji:"🗺️",tag:"b1",pos:"s.",ex:"We crossed the border into France early in the morning."},
  {it:"Respiro",en:"Breath",emoji:"💨",tag:"b1",pos:"s.",ex:"Take a deep breath before you start speaking."},
  {it:"Campagna",en:"Campaign",emoji:"📣",tag:"b1",pos:"s.",ex:"They launched a campaign to raise awareness of the issue."},
  {it:"Sfida",en:"Challenge",emoji:"🏔️",tag:"b1",pos:"s.",ex:"Learning a new language is a real challenge."},
  {it:"Conclusione",en:"Conclusion",emoji:"🏁",tag:"b1",pos:"s.",ex:"The report came to a very clear conclusion."},
  {it:"Conseguenza",en:"Consequence",emoji:"⚖️",tag:"b1",pos:"s.",ex:"There are serious consequences for missing the deadline."},
  {it:"Consumatore",en:"Consumer",emoji:"🛒",tag:"b1",pos:"s.",ex:"Consumers are increasingly choosing sustainable products."},
  {it:"Danno",en:"Damage",emoji:"💥",tag:"b1",pos:"s.",ex:"The storm caused serious damage to the roof."},
  {it:"Dubbio",en:"Doubt",emoji:"🤔",tag:"b1",pos:"s.",ex:"There is no doubt that she is the best candidate."},
  {it:"Obbligo",en:"Duty",emoji:"⚖️",tag:"b1",pos:"s.",ex:"It is your duty to report any accident you witness."},
  {it:"Sforzo",en:"Effort",emoji:"💪",tag:"b1",pos:"s.",ex:"She put a lot of effort into preparing the presentation."},
  {it:"Elezione",en:"Election",emoji:"🗳️",tag:"b1",pos:"s.",ex:"The election results will be announced tomorrow morning."},
  {it:"Emozione",en:"Emotion",emoji:"❤️",tag:"b1",pos:"s.",ex:"She found it difficult to hide her emotions."},
  {it:"Ambiente",en:"Environment",emoji:"🌿",tag:"b1",pos:"s.",ex:"We all have a responsibility to protect the environment."},
  {it:"Scambio",en:"Exchange",emoji:"🔄",tag:"b1",pos:"s.",ex:"She did a language exchange with a French student."},
  {it:"Fattore",en:"Factor",emoji:"🔑",tag:"b1",pos:"s.",ex:"Price is the most important factor for most buyers."},
  {it:"Generazione",en:"Generation",emoji:"👨‍👩‍👧",tag:"b1",pos:"s.",ex:"Each generation faces its own unique challenges."},
  {it:"Identità",en:"Identity",emoji:"🪪",tag:"b1",pos:"s.",ex:"Language is an important part of our cultural identity."},
  {it:"Impatto",en:"Impact",emoji:"💥",tag:"b1",pos:"s.",ex:"The new law will have a big impact on small businesses."},
  {it:"Influenza",en:"Influence",emoji:"💡",tag:"b1",pos:"s.",ex:"Music has had a huge influence on her life."},
  {it:"Intenzione",en:"Intention",emoji:"🎯",tag:"b1",pos:"s.",ex:"I had no intention of staying so late at the party."},
  {it:"Problema urgente",en:"Issue",emoji:"⚠️",tag:"b1",pos:"s.",ex:"Climate change is the most pressing issue of our time."},
  {it:"Posizione",en:"Location",emoji:"📍",tag:"b1",pos:"s.",ex:"The hotel is in a perfect location near the beach."},
  {it:"Perdita",en:"Loss",emoji:"📉",tag:"b1",pos:"s.",ex:"The company reported a loss of two million euros."},
  {it:"Motivazione",en:"Motivation",emoji:"🔥",tag:"b1",pos:"s.",ex:"Her main motivation is to help other people."},
  {it:"Nazione",en:"Nation",emoji:"🏳️",tag:"b1",pos:"s.",ex:"People from every nation came together for the event."},
  {it:"Quartiere",en:"Neighbourhood",emoji:"🏘️",tag:"b1",pos:"s.",ex:"She lives in a very friendly neighbourhood."},
  {it:"Occasione",en:"Occasion",emoji:"🎉",tag:"b1",pos:"s.",ex:"A job interview is an occasion to show your best qualities."},
  {it:"Passione",en:"Passion",emoji:"❤️",tag:"b1",pos:"s.",ex:"She has a real passion for art and music."},
  {it:"Prestazione",en:"Performance",emoji:"🎭",tag:"b1",pos:"s.",ex:"His performance in the exam was excellent."},
  {it:"Piacere",en:"Pleasure",emoji:"😊",tag:"b1",pos:"s.",ex:"It was a real pleasure to meet you at the conference."},
  {it:"Politica",en:"Policy",emoji:"📋",tag:"b1",pos:"s.",ex:"The company has a strict policy on working from home."},
  {it:"Pressione",en:"Pressure",emoji:"💢",tag:"b1",pos:"s.",ex:"There is a lot of pressure to perform well at work."},
  {it:"Priorità",en:"Priority",emoji:"🥇",tag:"b1",pos:"s.",ex:"Health should always be your number one priority."},
  {it:"Profitto",en:"Profit",emoji:"💰",tag:"b1",pos:"s.",ex:"The company made a large profit last year."},
  {it:"Proprietà",en:"Property",emoji:"🏠",tag:"b1",pos:"s.",ex:"Property prices in the city have risen sharply."},
  {it:"Qualifica",en:"Qualification",emoji:"🎓",tag:"b1",pos:"s.",ex:"You need a specific qualification to work in this field."},
  {it:"Realtà",en:"Reality",emoji:"🌍",tag:"b1",pos:"s.",ex:"The reality of living abroad is very different from the idea."},
  {it:"Risorse",en:"Resource",emoji:"🏦",tag:"b1",pos:"s.",ex:"Time is the most valuable resource any of us has."},
  {it:"Rispetto",en:"Respect",emoji:"🎖️",tag:"b1",pos:"s.",ex:"Mutual respect is the foundation of any good relationship."},
  {it:"Responsabilità",en:"Responsibility",emoji:"⚖️",tag:"b1",pos:"s.",ex:"Taking responsibility for your mistakes is very important."},
  {it:"Rischio",en:"Risk",emoji:"⚠️",tag:"b1",pos:"s.",ex:"There is always a risk of failure when starting a business."},
  {it:"Sicurezza",en:"Safety",emoji:"🦺",tag:"b1",pos:"s.",ex:"The safety of passengers is always our top priority."},
  {it:"Statistica",en:"Statistic",emoji:"📊",tag:"b1",pos:"s.",ex:"This statistic shows that the situation is improving."},
  {it:"Stress",en:"Stress",emoji:"😓",tag:"b1",pos:"s.",ex:"Work-related stress is a very common problem today."},
  {it:"Tema",en:"Theme",emoji:"🎨",tag:"b1",pos:"s.",ex:"The main theme of the novel is the search for identity."},
  {it:"Teoria",en:"Theory",emoji:"💡",tag:"b1",pos:"s.",ex:"In theory the plan sounds good, but in practice it may fail."},
  {it:"Verità",en:"Truth",emoji:"✅",tag:"b1",pos:"s.",ex:"It is always better to tell the truth."},
  {it:"Vittima",en:"Victim",emoji:"😔",tag:"b1",pos:"s.",ex:"She was the victim of a serious misunderstanding."},
  // B1 AGGETTIVI
  {it:"Assoluto",en:"Absolute",emoji:"💯",tag:"b1",pos:"agg.",ex:"It was an absolute pleasure to work with you."},
  {it:"Avanzato",en:"Advanced",emoji:"📈",tag:"b1",pos:"agg.",ex:"This course is designed for advanced learners."},
  {it:"Consapevole",en:"Aware",emoji:"👁️",tag:"b1",pos:"agg.",ex:"Are you aware of the risks involved in this project?"},
  {it:"Coraggioso",en:"Brave",emoji:"🦁",tag:"b1",pos:"agg.",ex:"It was very brave of her to speak in public for the first time."},
  {it:"Calmo",en:"Calm",emoji:"😌",tag:"b1",pos:"agg.",ex:"Try to stay calm when things go wrong."},
  {it:"Fiducioso",en:"Confident",emoji:"😊",tag:"b1",pos:"agg.",ex:"She felt confident going into the interview."},
  {it:"Conveniente",en:"Convenient",emoji:"✅",tag:"b1",pos:"agg.",ex:"Is Thursday morning convenient for the meeting?"},
  {it:"Attuale",en:"Current",emoji:"📅",tag:"b1",pos:"agg.",ex:"What is the current situation in the company?"},
  {it:"Determinato",en:"Determined",emoji:"🏋️",tag:"b1",pos:"agg.",ex:"She was determined to pass the exam this time."},
  {it:"Efficace",en:"Effective",emoji:"✅",tag:"b1",pos:"agg.",ex:"Regular revision is the most effective way to prepare."},
  {it:"Essenziale",en:"Essential",emoji:"⭐",tag:"b1",pos:"agg.",ex:"Good communication skills are essential in any job."},
  {it:"Affascinante",en:"Fascinating",emoji:"✨",tag:"b1",pos:"agg.",ex:"She found the history of the city absolutely fascinating."},
  {it:"Globale",en:"Global",emoji:"🌍",tag:"b1",pos:"agg.",ex:"Climate change is a global problem that needs global solutions."},
  {it:"Grato",en:"Grateful",emoji:"🙏",tag:"b1",pos:"agg.",ex:"I am very grateful for all the help you have given me."},
  {it:"Onesto",en:"Honest",emoji:"✅",tag:"b1",pos:"agg.",ex:"She is always completely honest with her clients."},
  {it:"Impressionante",en:"Impressive",emoji:"😮",tag:"b1",pos:"agg.",ex:"The results of the project were truly impressive."},
  {it:"Simpatico",en:"Kind",emoji:"❤️",tag:"b1",pos:"agg.",ex:"It was very kind of you to help me with my bag."},
  {it:"Legale",en:"Legal",emoji:"⚖️",tag:"b1",pos:"agg.",ex:"Is it legal to film people in a public place?"},
  {it:"Mentale",en:"Mental",emoji:"🧠",tag:"b1",pos:"agg.",ex:"Mental health is as important as physical health."},
  {it:"Ovvio",en:"Obvious",emoji:"💡",tag:"b1",pos:"agg.",ex:"It was obvious from his expression that he was unhappy."},
  {it:"Organizzato",en:"Organized",emoji:"📁",tag:"b1",pos:"agg.",ex:"She is one of the most organized people I have ever met."},
  {it:"Piacevole",en:"Pleasant",emoji:"😊",tag:"b1",pos:"agg.",ex:"We had a very pleasant evening at their house."},
  {it:"Potente",en:"Powerful",emoji:"💪",tag:"b1",pos:"agg.",ex:"It was a very powerful speech that moved the audience."},
  {it:"Pratico",en:"Practical",emoji:"🔧",tag:"b1",pos:"agg.",ex:"He is very practical and always knows how to fix things."},
  {it:"Precedente",en:"Previous",emoji:"⬅️",tag:"b1",pos:"agg.",ex:"She has no previous experience in this field."},
  {it:"Orgoglioso",en:"Proud",emoji:"🦚",tag:"b1",pos:"agg.",ex:"Her parents were very proud of her achievements."},
  {it:"Rilassato",en:"Relaxed",emoji:"😌",tag:"b1",pos:"agg.",ex:"She felt very relaxed after the yoga class."},
  {it:"Affidabile",en:"Reliable",emoji:"🤝",tag:"b1",pos:"agg.",ex:"She is the most reliable member of the team."},
  {it:"Romantico",en:"Romantic",emoji:"❤️",tag:"b1",pos:"agg.",ex:"Venice is one of the most romantic cities in the world."},
  {it:"Scientifico",en:"Scientific",emoji:"🔬",tag:"b1",pos:"agg.",ex:"There is strong scientific evidence to support this theory."},
  {it:"Sensibile",en:"Sensible",emoji:"🧠",tag:"b1",pos:"agg.",ex:"That sounds like a very sensible idea."},
  {it:"Timido",en:"Shy",emoji:"🙈",tag:"b1",pos:"agg.",ex:"She was shy at first but became more confident over time."},
  {it:"Stressante",en:"Stressful",emoji:"😓",tag:"b1",pos:"agg.",ex:"Working to a tight deadline is very stressful."},
  {it:"Talentuoso",en:"Talented",emoji:"⭐",tag:"b1",pos:"agg.",ex:"She is an incredibly talented musician."},
  {it:"Tipico",en:"Typical",emoji:"📏",tag:"b1",pos:"agg.",ex:"This is a very typical Italian village."},
  {it:"Vario",en:"Various",emoji:"🎨",tag:"b1",pos:"agg.",ex:"The course covers various topics related to business English."},
  {it:"Preoccupato",en:"Worried",emoji:"😰",tag:"b1",pos:"agg.",ex:"She was very worried about the results of the medical test."},
  // B1 VERBI
  {it:"Ammettere",en:"Admit",emoji:"🙋",tag:"b1",pos:"v.",ex:"He finally admitted that he had made a mistake."},
  {it:"Ammirare",en:"Admire",emoji:"😍",tag:"b1",pos:"v.",ex:"I really admire her courage and determination."},
  {it:"Analizzare",en:"Analyse",emoji:"🔬",tag:"b1",pos:"v.",ex:"We need to analyse the data before making a decision."},
  {it:"Annunciare",en:"Announce",emoji:"📢",tag:"b1",pos:"v.",ex:"The company announced plans to open ten new stores."},
  {it:"Scusarsi",en:"Apologize",emoji:"🙇",tag:"b1",pos:"v.",ex:"He apologized for being late to the meeting."},
  {it:"Apprezzare",en:"Appreciate",emoji:"🙏",tag:"b1",pos:"v.",ex:"I really appreciate all the help you have given me."},
  {it:"Attrarre",en:"Attract",emoji:"🧲",tag:"b1",pos:"v.",ex:"The festival attracts thousands of visitors every year."},
  {it:"Vietare",en:"Ban",emoji:"🚫",tag:"b1",pos:"v.",ex:"The government has banned smoking in all public places."},
  {it:"Bloccare",en:"Block",emoji:"🚫",tag:"b1",pos:"v.",ex:"A lorry broke down and blocked the road for two hours."},
  {it:"Respirare",en:"Breathe",emoji:"💨",tag:"b1",pos:"v.",ex:"Breathe deeply and slowly to help you relax."},
  {it:"Affermare",en:"Claim",emoji:"💬",tag:"b1",pos:"v.",ex:"She claimed that she had never met him before."},
  {it:"Concentrarsi",en:"Concentrate",emoji:"🎯",tag:"b1",pos:"v.",ex:"It is hard to concentrate when there is so much noise."},
  {it:"Convincere",en:"Convince",emoji:"💬",tag:"b1",pos:"v.",ex:"She convinced her boss to try a new approach."},
  {it:"Definire",en:"Define",emoji:"📖",tag:"b1",pos:"v.",ex:"How would you define the word success?"},
  {it:"Consegnare",en:"Deliver",emoji:"📦",tag:"b1",pos:"v.",ex:"The parcel was delivered to the wrong address."},
  {it:"Dividere",en:"Divide",emoji:"➗",tag:"b1",pos:"v.",ex:"Divide the class into groups of four for the activity."},
  {it:"Donare",en:"Donate",emoji:"🎁",tag:"b1",pos:"v.",ex:"She donated a large amount of money to the local hospital."},
  {it:"Dubitare",en:"Doubt",emoji:"🤔",tag:"b1",pos:"v.",ex:"I doubt that he will arrive on time."},
  {it:"Incoraggiare",en:"Encourage",emoji:"👏",tag:"b1",pos:"v.",ex:"Her teacher encouraged her to apply for a scholarship."},
  {it:"Scappare",en:"Escape",emoji:"🏃",tag:"b1",pos:"v.",ex:"He escaped from the burning building through a window."},
  {it:"Esaminare",en:"Examine",emoji:"🔍",tag:"b1",pos:"v.",ex:"The doctor examined the patient very carefully."},
  {it:"Esplorare",en:"Explore",emoji:"🗺️",tag:"b1",pos:"v.",ex:"She loves to explore new places when she travels."},
  {it:"Affrontare",en:"Face",emoji:"😤",tag:"b1",pos:"v.",ex:"She had to face some very difficult decisions at work."},
  {it:"Raccogliere",en:"Gather",emoji:"👥",tag:"b1",pos:"v.",ex:"A large crowd gathered in the square to hear the speech."},
  {it:"Ignorare",en:"Ignore",emoji:"🚫",tag:"b1",pos:"v.",ex:"She completely ignored his advice and did it her own way."},
  {it:"Indicare",en:"Indicate",emoji:"👉",tag:"b1",pos:"v.",ex:"The survey results indicate a clear change in attitude."},
  {it:"Investire",en:"Invest",emoji:"💹",tag:"b1",pos:"v.",ex:"She invested her savings in property ten years ago."},
  {it:"Investigare",en:"Investigate",emoji:"🔍",tag:"b1",pos:"v.",ex:"The police are investigating a series of robberies."},
  {it:"Mentire",en:"Lie",emoji:"🤥",tag:"b1",pos:"v.",ex:"He lied about his age on the application form."},
  {it:"Accadere / Venire in mente",en:"Occur",emoji:"💡",tag:"b1",pos:"v.",ex:"It did not occur to me that she might be upset."},
  {it:"Persuadere",en:"Persuade",emoji:"💬",tag:"b1",pos:"v.",ex:"She persuaded her manager to give her a pay rise."},
  {it:"Prevedere",en:"Predict",emoji:"🔮",tag:"b1",pos:"v.",ex:"It is very difficult to predict what will happen next."},
  {it:"Fingere",en:"Pretend",emoji:"🎭",tag:"b1",pos:"v.",ex:"He pretended to be ill to avoid going to school."},
  {it:"Punire",en:"Punish",emoji:"⚖️",tag:"b1",pos:"v.",ex:"The students were punished for cheating in the exam."},
  {it:"Lasciare / Mollare",en:"Quit",emoji:"🚪",tag:"b1",pos:"v.",ex:"She decided to quit her job and start her own business."},
  {it:"Reagire",en:"React",emoji:"💥",tag:"b1",pos:"v.",ex:"How did he react when he heard the news?"},
  {it:"Rendersi conto",en:"Realize",emoji:"💡",tag:"b1",pos:"v.",ex:"I only realized I had left my keys when I got home."},
  {it:"Rifiutare",en:"Reject",emoji:"❌",tag:"b1",pos:"v.",ex:"Her application was rejected because of her lack of experience."},
  {it:"Rilasciare",en:"Release",emoji:"🕊️",tag:"b1",pos:"v.",ex:"The new album will be released in March."},
  {it:"Rimanere",en:"Remain",emoji:"🏠",tag:"b1",pos:"v.",ex:"Please remain seated until the plane has come to a stop."},
  {it:"Ricordare",en:"Remember",emoji:"🧠",tag:"b1",pos:"v.",ex:"Do you remember where you put your keys?"},
  {it:"Ricordare a qualcuno",en:"Remind",emoji:"🔔",tag:"b1",pos:"v.",ex:"Can you remind me to call the doctor tomorrow morning?"},
  {it:"Ritirarsi",en:"Retire",emoji:"🏖️",tag:"b1",pos:"v.",ex:"She retired from her teaching career at the age of sixty-five."},
  {it:"Ripassare",en:"Revise",emoji:"📖",tag:"b1",pos:"v.",ex:"She spent the whole weekend revising for her exams."},
  {it:"Sopravvivere",en:"Survive",emoji:"🌿",tag:"b1",pos:"v.",ex:"The company managed to survive despite the economic crisis."},
  {it:"Tradurre",en:"Translate",emoji:"🌐",tag:"b1",pos:"v.",ex:"Can you translate this paragraph into Italian for me?"},
  {it:"Trattare",en:"Treat",emoji:"💊",tag:"b1",pos:"v.",ex:"The hospital treated over two hundred patients last week."},
  {it:"Votare",en:"Vote",emoji:"🗳️",tag:"b1",pos:"v.",ex:"Remember to vote in the local elections next month."},
  // B2 SOSTANTIVI
  {it:"Capacità",en:"Capability",emoji:"💪",tag:"b2",pos:"s.",ex:"She has the capability to lead the whole department."},
  {it:"Impegno",en:"Commitment",emoji:"⚖️",tag:"b2",pos:"s.",ex:"Success requires total commitment to your goals."},
  {it:"Concetto",en:"Concept",emoji:"💡",tag:"b2",pos:"s.",ex:"The concept of free trade is very important in economics."},
  {it:"Preoccupazione",en:"Concern",emoji:"😟",tag:"b2",pos:"s.",ex:"Her main concern was the safety of her children."},
  {it:"Conflitto",en:"Conflict",emoji:"⚔️",tag:"b2",pos:"s.",ex:"There is often a conflict between work and personal life."},
  {it:"Debito",en:"Debt",emoji:"💳",tag:"b2",pos:"s.",ex:"Many young people graduate with significant student debt."},
  {it:"Richiesta",en:"Demand",emoji:"📢",tag:"b2",pos:"s.",ex:"There is a huge demand for skilled workers in this field."},
  {it:"Bozza",en:"Draft",emoji:"✏️",tag:"b2",pos:"s.",ex:"Please send me the first draft of the report by Friday."},
  {it:"Efficienza",en:"Efficiency",emoji:"⚡",tag:"b2",pos:"s.",ex:"We need to improve the efficiency of the production process."},
  {it:"Entusiasmo",en:"Enthusiasm",emoji:"🔥",tag:"b2",pos:"s.",ex:"Her enthusiasm for the project inspired the whole team."},
  {it:"Spesa",en:"Expense",emoji:"💰",tag:"b2",pos:"s.",ex:"The travel expenses were much higher than expected."},
  {it:"Aspettativa",en:"Expectation",emoji:"🎯",tag:"b2",pos:"s.",ex:"The results exceeded everyone expectations."},
  {it:"Fallimento",en:"Failure",emoji:"❌",tag:"b2",pos:"s.",ex:"Failure is often the best teacher if you learn from it."},
  {it:"Reddito",en:"Income",emoji:"💰",tag:"b2",pos:"s.",ex:"Her income has increased significantly over the last five years."},
  {it:"Intuizione",en:"Insight",emoji:"💡",tag:"b2",pos:"s.",ex:"The research provides fascinating insights into human behaviour."},
  {it:"Istituzione",en:"Institution",emoji:"🏛️",tag:"b2",pos:"s.",ex:"The university is one of the oldest educational institutions."},
  {it:"Assicurazione",en:"Insurance",emoji:"🛡️",tag:"b2",pos:"s.",ex:"Make sure you have travel insurance before you go abroad."},
  {it:"Iniziativa",en:"Initiative",emoji:"🚀",tag:"b2",pos:"s.",ex:"She took the initiative and organised the whole event."},
  {it:"Giustizia",en:"Justice",emoji:"⚖️",tag:"b2",pos:"s.",ex:"Everyone has the right to justice regardless of their background."},
  {it:"Paesaggio",en:"Landscape",emoji:"🌅",tag:"b2",pos:"s.",ex:"The landscape of the Scottish Highlands is breathtaking."},
  {it:"Lancio",en:"Launch",emoji:"🚀",tag:"b2",pos:"s.",ex:"The product launch attracted a lot of media attention."},
  {it:"Prestito",en:"Loan",emoji:"💳",tag:"b2",pos:"s.",ex:"She took out a loan to pay for her university fees."},
  {it:"Maggioranza",en:"Majority",emoji:"📊",tag:"b2",pos:"s.",ex:"The vast majority of students passed the exam."},
  {it:"Missione",en:"Mission",emoji:"🎯",tag:"b2",pos:"s.",ex:"Our mission is to provide high-quality education to all."},
  {it:"Obiettivo",en:"Objective",emoji:"🎯",tag:"b2",pos:"s.",ex:"Our main objective is to reduce costs by fifteen percent."},
  {it:"Esito",en:"Outcome",emoji:"🏁",tag:"b2",pos:"s.",ex:"The outcome of the meeting was better than expected."},
  {it:"Schema",en:"Pattern",emoji:"🔄",tag:"b2",pos:"s.",ex:"There is a clear pattern in the data that we need to address."},
  {it:"Pensione",en:"Pension",emoji:"🏖️",tag:"b2",pos:"s.",ex:"She has been saving into a pension since she was twenty-five."},
  {it:"Fase",en:"Phase",emoji:"📊",tag:"b2",pos:"s.",ex:"We are now entering the second phase of the project."},
  {it:"Fenomeno",en:"Phenomenon",emoji:"🌪️",tag:"b2",pos:"s.",ex:"Social media is a global phenomenon that affects everyone."},
  {it:"Potenziale",en:"Potential",emoji:"🌱",tag:"b2",pos:"s.",ex:"She has enormous potential and will go far in her career."},
  {it:"Procedura",en:"Procedure",emoji:"📋",tag:"b2",pos:"s.",ex:"Please follow the correct procedure when reporting an incident."},
  {it:"Protezione",en:"Protection",emoji:"🛡️",tag:"b2",pos:"s.",ex:"The law provides protection for employees against unfair dismissal."},
  {it:"Acquisto",en:"Purchase",emoji:"🛒",tag:"b2",pos:"s.",ex:"Keep your receipt as proof of purchase."},
  {it:"Ricompensa",en:"Reward",emoji:"🏆",tag:"b2",pos:"s.",ex:"Hard work will always be rewarded in the end."},
  {it:"Settore",en:"Sector",emoji:"🏢",tag:"b2",pos:"s.",ex:"She works in the public sector as a nurse."},
  {it:"Sessione",en:"Session",emoji:"⏱️",tag:"b2",pos:"s.",ex:"The training session lasted three hours without a break."},
  {it:"Stato",en:"Status",emoji:"📊",tag:"b2",pos:"s.",ex:"What is the current status of the application?"},
  {it:"Strategia",en:"Strategy",emoji:"♟️",tag:"b2",pos:"s.",ex:"We need a clear strategy if we want to win the contract."},
  {it:"Lotta",en:"Struggle",emoji:"💪",tag:"b2",pos:"s.",ex:"It was a real struggle to balance work and family life."},
  {it:"Chirurgia",en:"Surgery",emoji:"🏥",tag:"b2",pos:"s.",ex:"She underwent major surgery last year and is now recovering well."},
  {it:"Simpatia",en:"Sympathy",emoji:"❤️",tag:"b2",pos:"s.",ex:"She showed great sympathy for the families affected by the disaster."},
  {it:"Minaccia",en:"Threat",emoji:"⚠️",tag:"b2",pos:"s.",ex:"Climate change poses a serious threat to the planet."},
  {it:"Tono",en:"Tone",emoji:"🎵",tag:"b2",pos:"s.",ex:"Please use a more professional tone in your emails."},
  {it:"Fiducia",en:"Trust",emoji:"🔐",tag:"b2",pos:"s.",ex:"Trust is the most important element in any relationship."},
  {it:"Vittoria",en:"Victory",emoji:"🏆",tag:"b2",pos:"s.",ex:"The victory was celebrated by the whole country."},
  {it:"Violenza",en:"Violence",emoji:"⚡",tag:"b2",pos:"s.",ex:"Violence is never an acceptable way to resolve a conflict."},
  {it:"Visione",en:"Vision",emoji:"👁️",tag:"b2",pos:"s.",ex:"The CEO shared her long-term vision for the company."},
  {it:"Salario",en:"Wage",emoji:"💰",tag:"b2",pos:"s.",ex:"The government increased the minimum wage last year."},
  {it:"Ricchezza",en:"Wealth",emoji:"💎",tag:"b2",pos:"s.",ex:"Education is the best path to long-term wealth."},
  // B2 AGGETTIVI
  {it:"Accurato",en:"Accurate",emoji:"🎯",tag:"b2",pos:"agg.",ex:"The weather forecast was surprisingly accurate this week."},
  {it:"Aggressivo",en:"Aggressive",emoji:"😤",tag:"b2",pos:"agg.",ex:"His aggressive attitude made the meeting very difficult."},
  {it:"Ansioso",en:"Anxious",emoji:"😰",tag:"b2",pos:"agg.",ex:"She was very anxious about the result of the interview."},
  {it:"Appropriato",en:"Appropriate",emoji:"✅",tag:"b2",pos:"agg.",ex:"Make sure you wear appropriate clothing for the occasion."},
  {it:"Artificiale",en:"Artificial",emoji:"🤖",tag:"b2",pos:"agg.",ex:"The lake is entirely artificial, built in the 1950s."},
  {it:"Ampio",en:"Broad",emoji:"↔️",tag:"b2",pos:"agg.",ex:"She has a very broad knowledge of world history."},
  {it:"Capace",en:"Capable",emoji:"💪",tag:"b2",pos:"agg.",ex:"She is fully capable of managing the project on her own."},
  {it:"Classico",en:"Classic",emoji:"📖",tag:"b2",pos:"agg.",ex:"This novel is considered a classic of modern literature."},
  {it:"Complicato",en:"Complicated",emoji:"🤯",tag:"b2",pos:"agg.",ex:"The instructions were far too complicated for most users."},
  {it:"Consapevole",en:"Conscious",emoji:"🧘",tag:"b2",pos:"agg.",ex:"She is very conscious of the environmental impact of her choices."},
  {it:"Costante",en:"Constant",emoji:"🔁",tag:"b2",pos:"agg.",ex:"She made constant improvements to her work throughout the year."},
  {it:"Contemporaneo",en:"Contemporary",emoji:"🎨",tag:"b2",pos:"agg.",ex:"She is one of the most respected contemporary artists."},
  {it:"Critico",en:"Critical",emoji:"⚠️",tag:"b2",pos:"agg.",ex:"It is critical that we solve this problem immediately."},
  {it:"Cruciale",en:"Crucial",emoji:"🔑",tag:"b2",pos:"agg.",ex:"This meeting is crucial for the future of the company."},
  {it:"Deliberato",en:"Deliberate",emoji:"🎯",tag:"b2",pos:"agg.",ex:"It was a deliberate decision to keep the meeting small."},
  {it:"Depresso",en:"Depressed",emoji:"😔",tag:"b2",pos:"agg.",ex:"She felt depressed after hearing the bad news."},
  {it:"Disperato",en:"Desperate",emoji:"😱",tag:"b2",pos:"agg.",ex:"He made a desperate attempt to save the project."},
  {it:"Drammatico",en:"Dramatic",emoji:"🎭",tag:"b2",pos:"agg.",ex:"There has been a dramatic change in the company fortunes."},
  {it:"Efficiente",en:"Efficient",emoji:"⚡",tag:"b2",pos:"agg.",ex:"She is a very efficient worker who always meets deadlines."},
  {it:"Emotivo",en:"Emotional",emoji:"❤️",tag:"b2",pos:"agg.",ex:"It was a very emotional speech that moved everyone to tears."},
  {it:"Intero",en:"Entire",emoji:"💯",tag:"b2",pos:"agg.",ex:"She spent the entire weekend working on the project."},
  {it:"Straordinario",en:"Extraordinary",emoji:"🌟",tag:"b2",pos:"agg.",ex:"She has achieved extraordinary things in a very short time."},
  {it:"Fondamentale",en:"Fundamental",emoji:"⭐",tag:"b2",pos:"agg.",ex:"Trust is fundamental to any healthy relationship."},
  {it:"Graduale",en:"Gradual",emoji:"📈",tag:"b2",pos:"agg.",ex:"There has been a gradual improvement in her performance."},
  {it:"Nocivo",en:"Harmful",emoji:"☠️",tag:"b2",pos:"agg.",ex:"Smoking is harmful to both your health and others around you."},
  {it:"Intenso",en:"Intense",emoji:"🔥",tag:"b2",pos:"agg.",ex:"The training was so intense that many people dropped out."},
  {it:"Logico",en:"Logical",emoji:"🧠",tag:"b2",pos:"agg.",ex:"The most logical solution is to renegotiate the contract."},
  {it:"Di lungo termine",en:"Long-term",emoji:"📅",tag:"b2",pos:"agg.",ex:"We need to think about the long-term consequences of this decision."},
  {it:"Enorme / Imponente",en:"Massive",emoji:"🏔️",tag:"b2",pos:"agg.",ex:"There has been a massive increase in online shopping."},
  {it:"Militare",en:"Military",emoji:"🎖️",tag:"b2",pos:"agg.",ex:"The government is increasing military spending next year."},
  {it:"Misterioso",en:"Mysterious",emoji:"🔍",tag:"b2",pos:"agg.",ex:"The cause of the accident remains mysterious."},
  {it:"Numerosi / Molti",en:"Numerous",emoji:"🔢",tag:"b2",pos:"agg.",ex:"She has received numerous awards for her work."},
  {it:"Permanente",en:"Permanent",emoji:"♾️",tag:"b2",pos:"agg.",ex:"She has finally found permanent employment after months of searching."},
  {it:"Puro",en:"Pure",emoji:"💎",tag:"b2",pos:"agg.",ex:"The air in the mountains is wonderfully pure and fresh."},
  {it:"Rapido",en:"Rapid",emoji:"⚡",tag:"b2",pos:"agg.",ex:"The rapid growth of the company surprised everyone."},
  {it:"Realistico",en:"Realistic",emoji:"🎯",tag:"b2",pos:"agg.",ex:"We need to set realistic targets for the next quarter."},
  {it:"Ragionevole",en:"Reasonable",emoji:"🧮",tag:"b2",pos:"agg.",ex:"The price is very reasonable for the quality you get."},
  {it:"Rilevante",en:"Relevant",emoji:"🔗",tag:"b2",pos:"agg.",ex:"Please make sure all information in the report is relevant."},
  {it:"Sicuro",en:"Secure",emoji:"🔐",tag:"b2",pos:"agg.",ex:"Make sure your password is secure and hard to guess."},
  {it:"Sensibile",en:"Sensitive",emoji:"💙",tag:"b2",pos:"agg.",ex:"He is very sensitive about criticism of his work."},
  {it:"Grave",en:"Severe",emoji:"⚠️",tag:"b2",pos:"agg.",ex:"The region has been hit by severe flooding this week."},
  {it:"Significativo",en:"Significant",emoji:"📊",tag:"b2",pos:"agg.",ex:"There has been a significant improvement in her results."},
  {it:"Sincero",en:"Sincere",emoji:"❤️",tag:"b2",pos:"agg.",ex:"She gave a very sincere apology for her mistake."},
  {it:"Stabile",en:"Stable",emoji:"⚖️",tag:"b2",pos:"agg.",ex:"The patient condition is now stable after surgery."},
  {it:"Rigido",en:"Strict",emoji:"📏",tag:"b2",pos:"agg.",ex:"The school has very strict rules about attendance."},
  {it:"Duro / Difficile",en:"Tough",emoji:"💪",tag:"b2",pos:"agg.",ex:"It was a tough decision but ultimately the right one."},
  {it:"Urbano",en:"Urban",emoji:"🏙️",tag:"b2",pos:"agg.",ex:"Urban areas tend to have better public transport."},
  {it:"Vasto / Immensa",en:"Vast",emoji:"🌊",tag:"b2",pos:"agg.",ex:"There is a vast difference between the two approaches."},
  {it:"Virtuale",en:"Virtual",emoji:"💻",tag:"b2",pos:"agg.",ex:"She attended the conference virtually from her home office."},
  {it:"Vitale",en:"Vital",emoji:"❤️",tag:"b2",pos:"agg.",ex:"Exercise is vital for maintaining good mental health."},
  {it:"Disposto",en:"Willing",emoji:"🤝",tag:"b2",pos:"agg.",ex:"Are you willing to work overtime if needed?"},
  // B2 VERBI
  {it:"Abbandonare",en:"Abandon",emoji:"🚪",tag:"b2",pos:"v.",ex:"They had to abandon the plan when costs became too high."},
  {it:"Adattare",en:"Adapt",emoji:"🔄",tag:"b2",pos:"v.",ex:"She quickly adapted to her new working environment."},
  {it:"Accusare",en:"Accuse",emoji:"👉",tag:"b2",pos:"v.",ex:"He was accused of stealing money from the company."},
  {it:"Riconoscere",en:"Acknowledge",emoji:"🙋",tag:"b2",pos:"v.",ex:"She acknowledged that the mistake was her fault."},
  {it:"Acquisire",en:"Acquire",emoji:"🤝",tag:"b2",pos:"v.",ex:"The company acquired a smaller competitor last year."},
  {it:"Adottare",en:"Adopt",emoji:"❤️",tag:"b2",pos:"v.",ex:"The committee adopted a new strategy for the coming year."},
  {it:"Alterare",en:"Alter",emoji:"🔄",tag:"b2",pos:"v.",ex:"The new regulations will alter the way companies operate."},
  {it:"Valutare",en:"Assess",emoji:"📊",tag:"b2",pos:"v.",ex:"Teachers assess students regularly throughout the year."},
  {it:"Assumere",en:"Assume",emoji:"🤔",tag:"b2",pos:"v.",ex:"Do not assume that everyone agrees with your point of view."},
  {it:"Trasmettere",en:"Broadcast",emoji:"📡",tag:"b2",pos:"v.",ex:"The match will be broadcast live on national television."},
  {it:"Calcolare",en:"Calculate",emoji:"🔢",tag:"b2",pos:"v.",ex:"Can you calculate how much the project will cost?"},
  {it:"Annullare",en:"Cancel",emoji:"❌",tag:"b2",pos:"v.",ex:"The flight was cancelled because of bad weather conditions."},
  {it:"Catturare",en:"Capture",emoji:"📸",tag:"b2",pos:"v.",ex:"The photograph captured a truly special moment."},
  {it:"Crollare",en:"Collapse",emoji:"💥",tag:"b2",pos:"v.",ex:"The old bridge collapsed during the heavy floods."},
  {it:"Condurre",en:"Conduct",emoji:"📋",tag:"b2",pos:"v.",ex:"The university conducted research into the effects of sleep."},
  {it:"Contribuire",en:"Contribute",emoji:"🤲",tag:"b2",pos:"v.",ex:"Everyone can contribute to making the workplace better."},
  {it:"Dichiarare",en:"Declare",emoji:"📢",tag:"b2",pos:"v.",ex:"The government declared a state of emergency."},
  {it:"Declinare / Diminuire",en:"Decline",emoji:"📉",tag:"b2",pos:"v.",ex:"She politely declined the invitation to the conference."},
  {it:"Dimostrare",en:"Demonstrate",emoji:"✊",tag:"b2",pos:"v.",ex:"The data demonstrates a clear link between diet and health."},
  {it:"Negare",en:"Deny",emoji:"❌",tag:"b2",pos:"v.",ex:"He denied any involvement in the scandal."},
  {it:"Meritare",en:"Deserve",emoji:"🏆",tag:"b2",pos:"v.",ex:"She deserves great credit for everything she has achieved."},
  {it:"Distribuire",en:"Distribute",emoji:"📦",tag:"b2",pos:"v.",ex:"The leaflets were distributed to every house in the street."},
  {it:"Dominare",en:"Dominate",emoji:"👑",tag:"b2",pos:"v.",ex:"She dominated the conversation throughout the meeting."},
  {it:"Permettere",en:"Enable",emoji:"✅",tag:"b2",pos:"v.",ex:"New technology has enabled people to work from anywhere."},
  {it:"Migliorare",en:"Enhance",emoji:"📈",tag:"b2",pos:"v.",ex:"Regular practice will enhance your language skills significantly."},
  {it:"Garantire",en:"Ensure",emoji:"✅",tag:"b2",pos:"v.",ex:"Please ensure that all documents are completed correctly."},
  {it:"Valutare",en:"Evaluate",emoji:"📊",tag:"b2",pos:"v.",ex:"We need to evaluate the results before making any changes."},
  {it:"Esporre",en:"Expose",emoji:"🔍",tag:"b2",pos:"v.",ex:"The investigation exposed serious corruption in the organization."},
  {it:"Estendere",en:"Extend",emoji:"📏",tag:"b2",pos:"v.",ex:"They have agreed to extend the deadline by two weeks."},
  {it:"Fondare",en:"Found",emoji:"🏛️",tag:"b2",pos:"v.",ex:"The company was founded over one hundred years ago."},
  {it:"Generare",en:"Generate",emoji:"⚡",tag:"b2",pos:"v.",ex:"The new campaign generated a lot of interest and attention."},
  {it:"Garantire",en:"Guarantee",emoji:"✅",tag:"b2",pos:"v.",ex:"I cannot guarantee that the work will be finished on time."},
  {it:"Gestire",en:"Handle",emoji:"🛠️",tag:"b2",pos:"v.",ex:"She knows exactly how to handle difficult situations at work."},
  {it:"Esitare",en:"Hesitate",emoji:"🤔",tag:"b2",pos:"v.",ex:"Do not hesitate to contact me if you need any help."},
  {it:"Implicare",en:"Imply",emoji:"💭",tag:"b2",pos:"v.",ex:"What are you implying, that I am wrong?"},
  {it:"Imporre",en:"Impose",emoji:"⚖️",tag:"b2",pos:"v.",ex:"The government has imposed new restrictions on travel."},
  {it:"Impressionare",en:"Impress",emoji:"😮",tag:"b2",pos:"v.",ex:"Her performance at the interview impressed the whole panel."},
  {it:"Insistere",en:"Insist",emoji:"💪",tag:"b2",pos:"v.",ex:"She insisted on paying for dinner, which was very kind."},
  {it:"Ispirare",en:"Inspire",emoji:"✨",tag:"b2",pos:"v.",ex:"Her story of success has inspired many young people."},
  {it:"Interpretare",en:"Interpret",emoji:"🌐",tag:"b2",pos:"v.",ex:"The results can be interpreted in several different ways."},
  {it:"Interrompere",en:"Interrupt",emoji:"✋",tag:"b2",pos:"v.",ex:"Please do not interrupt while someone else is speaking."},
  {it:"Giustificare",en:"Justify",emoji:"⚖️",tag:"b2",pos:"v.",ex:"Can you justify why the project went over budget?"},
  {it:"Mantenere",en:"Maintain",emoji:"🔧",tag:"b2",pos:"v.",ex:"It is important to maintain a healthy work-life balance."},
  {it:"Modificare",en:"Modify",emoji:"🔄",tag:"b2",pos:"v.",ex:"We may need to modify our plans based on the new information."},
  {it:"Monitorare",en:"Monitor",emoji:"👁️",tag:"b2",pos:"v.",ex:"Doctors will monitor her progress over the next few weeks."},
  {it:"Obbedire",en:"Obey",emoji:"✅",tag:"b2",pos:"v.",ex:"All employees are expected to obey the company rules."},
  {it:"Osservare",en:"Observe",emoji:"👁️",tag:"b2",pos:"v.",ex:"She observed the behaviour of the animals for three months."},
  {it:"Opporsi",en:"Oppose",emoji:"❌",tag:"b2",pos:"v.",ex:"Several members of the committee opposed the new proposal."},
  {it:"Delineare / Riassumere",en:"Outline",emoji:"✏️",tag:"b2",pos:"v.",ex:"Please outline your main arguments at the start of the essay."},
  {it:"Possedere",en:"Possess",emoji:"🏠",tag:"b2",pos:"v.",ex:"She possesses all the qualities needed for this role."},
  {it:"Preservare",en:"Preserve",emoji:"🛡️",tag:"b2",pos:"v.",ex:"It is our duty to preserve the natural environment."},
  {it:"Promuovere",en:"Promote",emoji:"📣",tag:"b2",pos:"v.",ex:"The campaign promoted healthy eating among young people."},
  {it:"Proporre",en:"Propose",emoji:"💍",tag:"b2",pos:"v.",ex:"She proposed a completely new approach to the problem."},
  {it:"Perseguire / Dedicarsi a",en:"Pursue",emoji:"🏃",tag:"b2",pos:"v.",ex:"She decided to pursue a career in medicine."},
  {it:"Recuperare",en:"Recover",emoji:"🌱",tag:"b2",pos:"v.",ex:"It took her six months to recover from the operation."},
  {it:"Rammentare / Richiamare alla mente",en:"Recall",emoji:"🧠",tag:"b2",pos:"v.",ex:"I cannot recall where I first met her."},
  {it:"Registrare",en:"Register",emoji:"📋",tag:"b2",pos:"v.",ex:"Please register for the course by the end of this week."},
  {it:"Rimpiangere",en:"Regret",emoji:"😔",tag:"b2",pos:"v.",ex:"She regrets not studying harder when she was at school."},
  {it:"Rivelare",en:"Reveal",emoji:"✨",tag:"b2",pos:"v.",ex:"The investigation revealed that the accounts had been falsified."},
  {it:"Resistere",en:"Resist",emoji:"💪",tag:"b2",pos:"v.",ex:"It is hard to resist the temptation to check your phone constantly."},
  {it:"Risolvere",en:"Resolve",emoji:"🧩",tag:"b2",pos:"v.",ex:"The two sides finally resolved their differences."},
  {it:"Trattenere",en:"Retain",emoji:"🔒",tag:"b2",pos:"v.",ex:"The company is working hard to retain its best employees."},
  {it:"Ricercare / Ricorrere a",en:"Seek",emoji:"🔍",tag:"b2",pos:"v.",ex:"She sought advice from a lawyer before signing the contract."},
  {it:"Stabilire",en:"Settle",emoji:"🏠",tag:"b2",pos:"v.",ex:"They decided to settle in the south of France permanently."},
  {it:"Scioccare",en:"Shock",emoji:"⚡",tag:"b2",pos:"v.",ex:"The news of his resignation shocked the whole company."},
  {it:"Inviare",en:"Submit",emoji:"📤",tag:"b2",pos:"v.",ex:"Please submit your application before the closing date."},
  {it:"Sospettare",en:"Suspect",emoji:"🔍",tag:"b2",pos:"v.",ex:"I suspect that the problem is more serious than it appears."},
  {it:"Trasformare",en:"Transform",emoji:"✨",tag:"b2",pos:"v.",ex:"New technology has transformed the way we communicate."},
  {it:"Trasferire",en:"Transfer",emoji:"🔄",tag:"b2",pos:"v.",ex:"She was transferred to the company office in Berlin."},
  {it:"Esortare / Spingere",en:"Urge",emoji:"💬",tag:"b2",pos:"v.",ex:"He urged his team to submit the project before the deadline."},
  {it:"Variare",en:"Vary",emoji:"🔀",tag:"b2",pos:"v.",ex:"Prices vary a lot depending on the time of year."},
  // ── PHRASAL VERBS B1 ─────────────────────────────────────────────────
  {it:"Svegliarsi",en:"Wake up",emoji:"⏰",tag:"phrasal-b1",pos:"phrasal",syn:"arise",ex:"I could not wake up this morning without coffee."},
  {it:"Alzarsi",en:"Get up",emoji:"🛏️",tag:"phrasal-b1",pos:"phrasal",syn:"rise",ex:"I usually get up at seven in the morning."},
  {it:"Accendere",en:"Turn on",emoji:"💡",tag:"phrasal-b1",pos:"phrasal",syn:"activate",ex:"Turn on the lights, it is too dark in here."},
  {it:"Spegnere",en:"Turn off",emoji:"🔌",tag:"phrasal-b1",pos:"phrasal",syn:"deactivate",ex:"Please turn off the TV before you go to bed."},
  {it:"Rinunciare",en:"Give up",emoji:"🚭",tag:"phrasal-b1",pos:"phrasal",syn:"abandon",ex:"Never give up on your dreams."},
  {it:"Scoprire",en:"Find out",emoji:"🔎",tag:"phrasal-b1",pos:"phrasal",syn:"discover",ex:"Did you find out why she was late?"},
  {it:"Continuare",en:"Carry on",emoji:"🚶",tag:"phrasal-b1",pos:"phrasal",syn:"continue",ex:"Carry on with your work, I will be back soon."},
  {it:"Andare d'accordo",en:"Get on with",emoji:"🤝",tag:"phrasal-b1",pos:"phrasal",syn:"relate to",ex:"She gets on really well with her colleagues."},
  {it:"Tornare",en:"Come back",emoji:"🔙",tag:"phrasal-b1",pos:"phrasal",syn:"return",ex:"She came back from holiday feeling refreshed."},
  {it:"Succedere",en:"Go on",emoji:"▶️",tag:"phrasal-b1",pos:"phrasal",syn:"happen",ex:"What is going on? Why is everyone upset?"},
  {it:"Badare a",en:"Look after",emoji:"👶",tag:"phrasal-b1",pos:"phrasal",syn:"care for",ex:"Can you look after my cat while I am away?"},
  {it:"Passare a prendere",en:"Pick up",emoji:"🤲",tag:"phrasal-b1",pos:"phrasal",syn:"collect",ex:"Can you pick me up at the airport?"},
  {it:"Esaurirsi",en:"Run out of",emoji:"⛽",tag:"phrasal-b1",pos:"phrasal",syn:"exhaust",ex:"We have run out of milk. Can you buy some?"},
  {it:"Calmarsi",en:"Calm down",emoji:"😮‍💨",tag:"phrasal-b1",pos:"phrasal",syn:"relax",ex:"Calm down! Everything will be fine."},
  {it:"Compilare",en:"Fill in",emoji:"📝",tag:"phrasal-b1",pos:"phrasal",syn:"complete",ex:"Please fill in this form with your personal details."},
  {it:"Liberarsi di",en:"Get rid of",emoji:"🗑️",tag:"phrasal-b1",pos:"phrasal",syn:"eliminate",ex:"It is time to get rid of those old clothes."},
  {it:"Aspettare con piacere",en:"Look forward to",emoji:"🎉",tag:"phrasal-b1",pos:"phrasal",syn:"anticipate",ex:"I am looking forward to seeing you next week."},
  {it:"Tollerare",en:"Put up with",emoji:"😤",tag:"phrasal-b1",pos:"phrasal",syn:"tolerate",ex:"I cannot put up with this noise any longer."},
  {it:"Crescere",en:"Grow up",emoji:"🌱",tag:"phrasal-b1",pos:"phrasal",syn:"mature",ex:"She grew up in a small town near Rome."},
  {it:"Recuperare",en:"Catch up",emoji:"🏃",tag:"phrasal-b1",pos:"phrasal",syn:"catch up",ex:"I need to catch up with the work I missed."},
  {it:"Uscire",en:"Go out",emoji:"🚪",tag:"phrasal-b1",pos:"phrasal",syn:"go outside",ex:"Let us go out for dinner tonight."},
  {it:"Tenersi in contatto",en:"Keep in touch",emoji:"📞",tag:"phrasal-b1",pos:"phrasal",syn:"stay in contact",ex:"Let us keep in touch after the course ends."},
  {it:"Iscriversi",en:"Sign up",emoji:"✍️",tag:"phrasal-b1",pos:"phrasal",syn:"register",ex:"Sign up for the free trial on our website."},
  {it:"Rallentare",en:"Slow down",emoji:"🐢",tag:"phrasal-b1",pos:"phrasal",syn:"decelerate",ex:"Slow down! You are driving too fast."},
  {it:"Tirarsi su",en:"Cheer up",emoji:"😊",tag:"phrasal-b1",pos:"phrasal",syn:"be happy",ex:"Cheer up! Things will get better soon."},
  {it:"Rimandare",en:"Put off",emoji:"⏰",tag:"phrasal-b1",pos:"phrasal",syn:"postpone",ex:"Do not put off your homework until tomorrow."},
  {it:"Indossare",en:"Put on",emoji:"👕",tag:"phrasal-b1",pos:"phrasal",syn:"wear",ex:"Put on your coat, it is cold outside."},
  {it:"Decollare",en:"Take off",emoji:"✈️",tag:"phrasal-b1",pos:"phrasal",syn:"depart",ex:"The plane took off two hours late."},
  {it:"Guastarsi",en:"Break down",emoji:"🚗",tag:"phrasal-b1",pos:"phrasal",syn:"fail",ex:"The car broke down on the motorway."},
  {it:"Allevare",en:"Bring up",emoji:"👨‍👧",tag:"phrasal-b1",pos:"phrasal",syn:"raise",ex:"She was brought up by her grandparents."},
  {it:"Dipendere da",en:"Depend on",emoji:"🔗",tag:"phrasal-b1",pos:"phrasal",syn:"rely on",ex:"It depends on the weather whether we go or not."},
  {it:"Fare il check-in",en:"Check in",emoji:"🏨",tag:"phrasal-b1",pos:"phrasal",syn:"register",ex:"We checked in to the hotel at noon."},
  {it:"Rilassarsi",en:"Chill out",emoji:"😎",tag:"phrasal-b1",pos:"phrasal",syn:"relax",ex:"After the exam she just wanted to chill out."},
  {it:"Tornare indietro",en:"Get back",emoji:"🔙",tag:"phrasal-b1",pos:"phrasal",syn:"return",ex:"When did you get back from your holiday?"},
  {it:"Scendere da",en:"Get off",emoji:"🚌",tag:"phrasal-b1",pos:"phrasal",syn:"alight",ex:"We get off the bus at the next stop."},
  {it:"Salire / Entrare",en:"Get in",emoji:"🚪",tag:"phrasal-b1",pos:"phrasal",syn:"enter",ex:"Get in the car, we are already late."},
  {it:"Consegnare",en:"Hand in",emoji:"📝",tag:"phrasal-b1",pos:"phrasal",syn:"submit",ex:"Please hand in your assignment by Friday."},
  {it:"Passare il tempo con",en:"Hang out",emoji:"👫",tag:"phrasal-b1",pos:"phrasal",syn:"socialise",ex:"We like to hang out at the park on weekends."},
  {it:"Sdraiarsi",en:"Lie down",emoji:"🛋️",tag:"phrasal-b1",pos:"phrasal",syn:"rest",ex:"You should lie down if you feel unwell."},
  {it:"Mettere via",en:"Put away",emoji:"📦",tag:"phrasal-b1",pos:"phrasal",syn:"store",ex:"Put away your phone during the lesson please."},
  {it:"Partire",en:"Set off",emoji:"🚀",tag:"phrasal-b1",pos:"phrasal",syn:"depart",ex:"We set off early to avoid the morning traffic."},
  {it:"Spegnere (interruttore)",en:"Switch off",emoji:"🔅",tag:"phrasal-b1",pos:"phrasal",syn:"deactivate",ex:"Switch off the lights when you leave the room."},
  {it:"Buttare via",en:"Throw away",emoji:"🗑️",tag:"phrasal-b1",pos:"phrasal",syn:"discard",ex:"Do not throw away that receipt, you may need it."},
  {it:"Provarsi (abiti)",en:"Try on",emoji:"👗",tag:"phrasal-b1",pos:"phrasal",syn:"wear to try",ex:"She tried on three dresses before choosing one."},
  {it:"Allenarsi",en:"Work out",emoji:"🏋️",tag:"phrasal-b1",pos:"phrasal",syn:"exercise",ex:"She works out at the gym three times a week."},
  {it:"Candidarsi per",en:"Go for",emoji:"🎯",tag:"phrasal-b1",pos:"phrasal",syn:"apply for",ex:"She decided to go for the promotion."},
  {it:"Spegnersi / Esplodere",en:"Go off",emoji:"💥",tag:"phrasal-b1",pos:"phrasal",syn:"activate",ex:"The alarm went off at six in the morning."},
  {it:"Riagganciare",en:"Hang up",emoji:"📵",tag:"phrasal-b1",pos:"phrasal",syn:"end a call",ex:"She hung up before I could say goodbye."},
  {it:"Fare una visita rapida",en:"Drop by",emoji:"🚪",tag:"phrasal-b1",pos:"phrasal",syn:"visit briefly",ex:"Drop by any time, you are always welcome."},
  {it:"Ammalarsi",en:"Come down with",emoji:"🤒",tag:"phrasal-b1",pos:"phrasal",syn:"contract",ex:"I think I am coming down with a cold."},
  // ── PHRASAL VERBS B2 ─────────────────────────────────────────────────
  {it:"Organizzare / Fondare",en:"Set up",emoji:"🏗️",tag:"phrasal-b2",pos:"phrasal",syn:"establish",ex:"We need to set up a meeting for next week."},
  {it:"Occuparsi di",en:"Deal with",emoji:"🗂️",tag:"phrasal-b2",pos:"phrasal",syn:"handle",ex:"You need to deal with this problem immediately."},
  {it:"Indagare su",en:"Look into",emoji:"📂",tag:"phrasal-b2",pos:"phrasal",syn:"investigate",ex:"The police will look into the matter carefully."},
  {it:"Presentarsi / Apparire",en:"Turn up",emoji:"🎪",tag:"phrasal-b2",pos:"phrasal",syn:"arrive",ex:"He turned up an hour late without any excuse."},
  {it:"Cercare informazioni",en:"Look up",emoji:"📖",tag:"phrasal-b2",pos:"phrasal",syn:"search",ex:"Look up the word in the dictionary if you need it."},
  {it:"Scoppiare",en:"Break out",emoji:"💥",tag:"phrasal-b2",pos:"phrasal",syn:"erupt",ex:"A fire broke out in the warehouse last night."},
  {it:"Presentarsi",en:"Show up",emoji:"👋",tag:"phrasal-b2",pos:"phrasal",syn:"appear",ex:"He did not show up to the interview."},
  {it:"Capire / Risolvere",en:"Figure out",emoji:"🧩",tag:"phrasal-b2",pos:"phrasal",syn:"understand",ex:"I cannot figure out how to use this software."},
  {it:"Farcela / Superare",en:"Get through",emoji:"💪",tag:"phrasal-b2",pos:"phrasal",syn:"overcome",ex:"It was hard, but we got through it together."},
  {it:"Eseguire / Effettuare",en:"Carry out",emoji:"📋",tag:"phrasal-b2",pos:"phrasal",syn:"conduct",ex:"The team carried out the plan successfully."},
  {it:"Finire per fare",en:"End up",emoji:"🏁",tag:"phrasal-b2",pos:"phrasal",syn:"result in",ex:"We got lost and ended up in the wrong city."},
  {it:"Prendere il controllo",en:"Take over",emoji:"👑",tag:"phrasal-b2",pos:"phrasal",syn:"assume control",ex:"A new manager took over the department."},
  {it:"Venire fuori / Presentarsi",en:"Come up",emoji:"⬆️",tag:"phrasal-b2",pos:"phrasal",syn:"arise",ex:"An unexpected problem came up at the last minute."},
  {it:"Eliminare / Tagliare",en:"Cut out",emoji:"✂️",tag:"phrasal-b2",pos:"phrasal",syn:"eliminate",ex:"The doctor told him to cut out sugar completely."},
  {it:"Andare d'accordo",en:"Get along",emoji:"🤝",tag:"phrasal-b2",pos:"phrasal",syn:"be compatible",ex:"My sister and I get along very well now."},
  {it:"Deludere",en:"Let down",emoji:"😞",tag:"phrasal-b2",pos:"phrasal",syn:"disappoint",ex:"He let me down by not keeping his promise."},
  {it:"Uscire / Essere pubblicato",en:"Come out",emoji:"📕",tag:"phrasal-b2",pos:"phrasal",syn:"be released",ex:"The new album came out last Friday."},
  {it:"Iniziare un hobby",en:"Take up",emoji:"🎸",tag:"phrasal-b2",pos:"phrasal",syn:"start",ex:"She took up yoga to reduce stress."},
  {it:"Risparmiare",en:"Save up",emoji:"💰",tag:"phrasal-b2",pos:"phrasal",syn:"accumulate",ex:"I am saving up for a holiday in Japan."},
  {it:"Cedere / Ritirarsi",en:"Back down",emoji:"↩️",tag:"phrasal-b2",pos:"phrasal",syn:"withdraw",ex:"He refused to back down from his position."},
  {it:"Affrontare difficoltà",en:"Cope with",emoji:"🧘",tag:"phrasal-b2",pos:"phrasal",syn:"manage",ex:"She had to cope with a lot of stress at work."},
  {it:"Costruire gradualmente",en:"Build up",emoji:"📈",tag:"phrasal-b2",pos:"phrasal",syn:"develop",ex:"She has been building up her confidence for months."},
  {it:"Risolvere un problema",en:"Work out",emoji:"🧩",tag:"phrasal-b2",pos:"phrasal",syn:"solve",ex:"I cannot work out how to fix this error."},
  {it:"Separarsi",en:"Break up",emoji:"💔",tag:"phrasal-b2",pos:"phrasal",syn:"separate",ex:"They broke up after two years together."},
  {it:"Bloccare / Ritardare",en:"Hold up",emoji:"🚦",tag:"phrasal-b2",pos:"phrasal",syn:"delay",ex:"I was held up in traffic for over an hour."},
  {it:"Continuare a fare",en:"Keep on",emoji:"🔁",tag:"phrasal-b2",pos:"phrasal",syn:"persist",ex:"He kept on talking even when nobody listened."},
  {it:"Mantenere il passo",en:"Keep up",emoji:"🏃",tag:"phrasal-b2",pos:"phrasal",syn:"maintain",ex:"Keep up the good work and you will succeed."},
  {it:"Riconciliarsi / Inventare",en:"Make up",emoji:"💄",tag:"phrasal-b2",pos:"phrasal",syn:"reconcile",ex:"They argued but made up the following day."},
  {it:"Sistemare / Risolvere",en:"Sort out",emoji:"🗂️",tag:"phrasal-b2",pos:"phrasal",syn:"resolve",ex:"We need to sort out this problem before Monday."},
  {it:"Rifiutare / Abbassare",en:"Turn down",emoji:"🔉",tag:"phrasal-b2",pos:"phrasal",syn:"decline",ex:"He turned down the job offer without hesitation."},
  {it:"Ammirare qualcuno",en:"Look up to",emoji:"🌟",tag:"phrasal-b2",pos:"phrasal",syn:"admire",ex:"I have always looked up to my older brother."},
  {it:"Affrontare / Gestire",en:"Take on",emoji:"📋",tag:"phrasal-b2",pos:"phrasal",syn:"undertake",ex:"She took on too much work and felt overwhelmed."},
  {it:"Lasciare andare",en:"Let go of",emoji:"🕊️",tag:"phrasal-b2",pos:"phrasal",syn:"release",ex:"You need to let go of the past and move on."},
  {it:"Accelerare",en:"Speed up",emoji:"🐇",tag:"phrasal-b2",pos:"phrasal",syn:"accelerate",ex:"Can you speed up? We are going to be late."},
  {it:"Provare / Sperimentare",en:"Try out",emoji:"🧪",tag:"phrasal-b2",pos:"phrasal",syn:"test",ex:"You should try out the new restaurant downtown."},
  {it:"Entrare con forza",en:"Break in",emoji:"🔓",tag:"phrasal-b2",pos:"phrasal",syn:"intrude",ex:"Someone broke in and stole the laptop."},
  {it:"Basarsi su",en:"Be based on",emoji:"📐",tag:"phrasal-b2",pos:"phrasal",syn:"derive from",ex:"The film is based on a true story."},
  {it:"Accedere",en:"Log in",emoji:"🔑",tag:"phrasal-b2",pos:"phrasal",syn:"sign in",ex:"You need to log in to access your account."},
  {it:"Disconnettersi",en:"Log out",emoji:"🔓",tag:"phrasal-b2",pos:"phrasal",syn:"sign out",ex:"Remember to log out when you use a public computer."},
];

export default CARDS;
